{
 "title": "Valkey Performance - Per Command",
 "tags": [
  "valkey",
  "benchmark"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "SET - P10, IO 9",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ', architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 10 AND io_threads = 9 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp\n"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 10 AND io_threads = 9 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GET - P10, IO 9",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 10 AND io_threads = 9 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 10 AND io_threads = 9 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SET - P1, IO 9",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ', architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 1 AND io_threads = 9 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp\n"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 1 AND io_threads = 9 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GET - P1, IO 9",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 1 AND io_threads = 9 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 1 AND io_threads = 9 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SET - P10, IO 1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 10 AND io_threads = 1 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp\n"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 10 AND io_threads = 1 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GET - P10, IO 1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 10 AND io_threads = 1 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 10 AND io_threads = 1 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "SET - P1, IO 1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 1 AND io_threads = 1 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp\n"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'SET' AND pipeline = 1 AND io_threads = 1 ORDER BY timestamp"
    }
   ]
  },
  {
   "title": "GET - P1, IO 1",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, AVG(rps) AS value, CONCAT(data_size, ' Bytes, ', io_threads, ' IO-Threads, ', pipeline,' Pipelining, ',  architecture) AS metric FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 1 AND io_threads = 1 GROUP BY timestamp, command, data_size, pipeline, clients, requests, cluster_mode, tls, io_threads, architecture ORDER BY timestamp"
    },
    {
     "dataset": "postgres",
     "rawSql": "SELECT timestamp AS time, commit AS commit_hash FROM benchmark_metrics WHERE $__timeFilter(timestamp) AND command = 'GET' AND pipeline = 1 AND io_threads = 1 ORDER BY timestamp"
    }
   ]
  }
 ]
}